### ISSUE TITLE
How to change update rate? 

### ISSUE THREAD

**Issue by mccarr** [lyndw/AssetTracker2#1]
Hi Lynd,
I have tried using your library and example to get the Asset Tracker 2 working at 10Hz. 
Within `setup()`, after `t.gpsOn()` , I send `gpsRate("10")`.

On the serial monitor I get the NoAck response when trying to set the gpsRate. It doesn't increase the update frequency either. I've tried moving the gpsRate() call around but still getting the same response. Do you have recommendations on how to set up the Asset Tracker V2 at 10Hz ?

Thanks
<img width="406" alt="gpsrate no acknowledge" src="https://user-images.githubusercontent.com/28975108/39810618-fa2990a6-5385-11e8-9192-53e229accc15.png">
<img width="361" alt="gpsrate set location" src="https://user-images.githubusercontent.com/28975108/39810629-ff765a94-5385-11e8-8574-30fa0375e13e.PNG">

**Comment by lyndw** [comment]
Hi,
It's been awhile since I worked on this and I don't have my development system set up now but I'll try to help.
There are a couple of things: You are passing a string to gpsRate() with the 10 in quotes. Remove the quotes.
Also, gpsRate() takes 2 parameters: the first is the measurement rate, the second is the rate of generation navigating solutions. I recommend using 1 for the second parameter. This results in generating one navigation solution for each measurement.

So your call should be gpsRate(10,1);

Here is a bit from the GPS device spec sheet about the rate command that you are triggering when calling gpsRate().

Good luck.

Lynd

31.11.24 UBX-CFG-RATE (0x06 0x08)
31.11.24.1 Navigation/Measurement Rate Settings
Message CFG-RATE
Description Navigation/Measurement Rate Settings
Firmware Supported on:
• u-blox 8 / u-blox M8 from protocol version 15 up to version 23.01
Type Get/Set
Comment This feature is not supported for the FTS product variant.
This message allows the user to alter the rate at which navigation solutions (and the
measurements that they depend on) are generated by the receiver. The calculation of the
navigation solution will always be aligned to the top of a second zero (first second of the
week) of the configured reference time system.
For protocol version 18 and later the navigation period is an integer multiple of the
measurement period.
• Each measurement triggers the measurements generation and raw data output.
• The navRate value defines that every nth measurement triggers a navigation epoch.
• The update rate has a direct influence on the power consumption. The more fixes that
are required, the more CPU power and communication resources are required.
• For most applications a 1 Hz update rate would be sufficient.
• When using Power Save Mode, measurement and navigation rate can differ from the
values configured here. See Measurement and navigation rate with Power Save Mode
UBX-13003221 - R13 Early Production Information Page 204 of 371
u-blox 8 / u-blox M8 Receiver Description - Manual
for details.
Header Class ID Length (Bytes) Payload Checksum
Message Structure 0xB5 0x62 0x06 0x08 6 see below CK_A CK_B
Payload Contents:
Byte Offset Number
Format
Scaling Name Unit Description
0 U2 - measRate ms The elapsed time between GNSS measurements,
which defines the rate, e.g. 100ms => 10Hz,
1000ms => 1Hz, 10000ms => 0.1Hz
2 U2 - navRate cycles The ratio between the number of
measurements and the number of navigation
solutions, e.g. 5 means five measurements for
every navigation solution. Max. value is 127.
(This parameter is ignored and the navRate is
fixed to 1 in protocol versions less than 18)

**Comment by lyndw** [comment]
Oops, didn't mean to close.

**Comment by mccarr** [comment]
Hi Lynd,
A couple of comments:
1) The gpsRate function which is in the example (not t.gpsRate) actually **must** take a String as an input. 
2) There is some mix up between _rate_ and _delay between measurements_. The function gpsRate would suggest I give a rate input in Hz. E.g. 10 Hz. However I notice that this number is sent as the "Time between measurements" variables in the implementation in UBLOXM8Q_GPS library. So when I give 10 as an input to gpsRate, it's setting 10 ms delay between measurements which is actually 100 Hz. There should be some sort of conversion from rate -> measurement delay somewhere.  The asset tracker cannot support 100Hz GPS frequency. I just tried putting gpsRate(100) and that worked! 
<img width="318" alt="incorrect frequency" src="https://user-images.githubusercontent.com/28975108/39917180-ff9ea07a-550c-11e8-85e8-b2bcd596efff.png">
<img width="205" alt="message acked" src="https://user-images.githubusercontent.com/28975108/39917192-03ed6922-550d-11e8-8d1b-cfb5727fb77e.PNG">

So this is more a bit of confusing naming then something fundamentally wrong. However, good to let others know in the future that gpsRate() actually takes the delay between measurements as input, not the rate. 

Thanks
